In [2]:
#词表到向量的转换函数
from numpy import *

def loadDataSet():
    postingList=[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
                 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
                 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
                 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
                 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
                 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
    classVec = [0,1,0,1,0,1]    #1 is abusive, 0 not
    return postingList,classVec

In [3]:
def createVocabList(dataSet):
    vocabSet = set([])
    for document in dataSet:
        vocabSet = vocabSet | set(document)
    return list(vocabSet)

In [4]:
def setOfWords2Vec(vocabList, inputSet):
    returnVec = [0]*len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)] = 1
        else: print("the word: %s is not in my Vocabulary!")%word
    return returnVec

In [5]:
postingList,classVec = loadDataSet()

In [6]:
myVocabList = createVocabList(postingList)

In [7]:
myVocabList

['please',
 'him',
 'steak',
 'food',
 'garbage',
 'to',
 'I',
 'maybe',
 'so',
 'mr',
 'is',
 'problems',
 'love',
 'my',
 'dalmation',
 'how',
 'help',
 'buying',
 'licks',
 'not',
 'park',
 'posting',
 'cute',
 'has',
 'flea',
 'stupid',
 'quit',
 'take',
 'stop',
 'worthless',
 'ate',
 'dog']

In [8]:
setOfWords2Vec(myVocabList, postingList[3])

[0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0]

In [1]:
#计算 p(ci / w) = [p(w|ci)*p(ci)]/p(w)

In [10]:
from numpy import * 
def trainNB0(trainMatrix, trainCategory):#输入文档单词向量矩阵（查完字典的）和文档类别
    numTrainDocs = len(trainMatrix)
    numWords = len(trainMatrix[0])
    pAbusive = sum(trainCategory)/float(numTrainDocs) #计算侮辱性文档的概率 p(1)
    p0Num = zeros(numWords)
    p1Num = zeros(numWords)
    p0Denom = 0.0
    p1Denom = 0.0
    
    for i in range(numTrainDocs):
        if trainCategory[i] == 1:
            p1Num += trainMatrix[i]
            p1Denom += sum(trainMatrix[i])
        else:
            p0Num += trainMatrix[i]
            p0Denom += sum(trainMatrix[i])
    p1Vect = p1Num/p1Denom 
    p0Vect = p0Num/p0Denom
    return p0Vect, p1Vect, pAbusive


def trainNB1(trainMatrix, trainCategory):#输入文档单词向量矩阵（查完字典的）和文档类别
    numTrainDocs = len(trainMatrix)
    numWords = len(trainMatrix[0])
    pAbusive = sum(trainCategory)/float(numTrainDocs) #计算侮辱性文档的概率 p(1)
#     p0Num = zeros(numWords)
#     p1Num = zeros(numWords)
#     p0Denom = 0.0
#     p1Denom = 0.0
    p0Num = ones(numWords)
    p1Num = ones(numWords)
    p0Denom = 2.0
    p1Denom = 2.0
    
    for i in range(numTrainDocs):
        if trainCategory[i] == 1:
            p1Num += trainMatrix[i]
            p1Denom += sum(trainMatrix[i])
        else:
            p0Num += trainMatrix[i]
            p0Denom += sum(trainMatrix[i])
    p1Vect = log(p1Num/p1Denom) #防止下溢出
    p0Vect = log(p0Num/p0Denom)
    return p0Vect, p1Vect, pAbusive

In [11]:
from numpy import * 
listOPosts, listClasses = loadDataSet()

In [12]:
myVocabList = createVocabList(listOPosts)

In [13]:
trainMat = []
for postinDoc in listOPosts:
    trainMat.append(setOfWords2Vec(myVocabList, postinDoc))

In [14]:
p0V, p1V, pAb = trainNB0(trainMat, listClasses)

In [15]:
p0V, p1V, pAb

(array([0.04166667, 0.08333333, 0.04166667, 0.        , 0.        ,
        0.04166667, 0.04166667, 0.        , 0.04166667, 0.04166667,
        0.04166667, 0.04166667, 0.04166667, 0.125     , 0.04166667,
        0.04166667, 0.04166667, 0.        , 0.04166667, 0.        ,
        0.        , 0.        , 0.04166667, 0.04166667, 0.04166667,
        0.        , 0.        , 0.        , 0.04166667, 0.        ,
        0.04166667, 0.04166667]),
 array([0.        , 0.05263158, 0.        , 0.05263158, 0.05263158,
        0.05263158, 0.        , 0.05263158, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.05263158, 0.        , 0.05263158,
        0.05263158, 0.05263158, 0.        , 0.        , 0.        ,
        0.15789474, 0.05263158, 0.05263158, 0.05263158, 0.10526316,
        0.        , 0.10526316]),
 0.5)

In [16]:
p1V[myVocabList.index("stupid")]

0.15789473684210525

In [17]:
p1V[myVocabList.index("stupid")]

0.15789473684210525

In [57]:
p0V, p1V, pAb = trainNB1(trainMat, listClasses)

In [58]:
p0V, p1V, pAb 

(array([-2.56494936, -3.25809654, -3.25809654, -2.56494936, -2.56494936,
        -3.25809654, -3.25809654, -3.25809654, -2.56494936, -2.56494936,
        -3.25809654, -3.25809654, -1.87180218, -2.56494936, -3.25809654,
        -3.25809654, -3.25809654, -2.56494936, -2.56494936, -2.56494936,
        -2.56494936, -2.15948425, -2.56494936, -2.56494936, -2.56494936,
        -3.25809654, -2.56494936, -2.56494936, -2.56494936, -2.56494936,
        -2.56494936, -2.56494936]),
 array([-3.04452244, -1.94591015, -2.35137526, -3.04452244, -1.94591015,
        -1.65822808, -2.35137526, -2.35137526, -3.04452244, -3.04452244,
        -2.35137526, -2.35137526, -3.04452244, -3.04452244, -2.35137526,
        -2.35137526, -2.35137526, -3.04452244, -3.04452244, -3.04452244,
        -3.04452244, -2.35137526, -3.04452244, -3.04452244, -3.04452244,
        -2.35137526, -2.35137526, -3.04452244, -3.04452244, -3.04452244,
        -2.35137526, -3.04452244]),
 0.5)

In [59]:
p1V.max()

-1.6582280766035324

In [60]:
p1V[myVocabList.index("stupid")]

-1.6582280766035324

In [ ]:
#计算 p(ci / w) = [p(w|ci)*p(ci)]/p(w)

In [19]:
def classifyNB(vec2Classify, p0Vec, p1Vec, pClass1):
    #计算[p(w|c1)*p(c1)]
    p1 = sum(vec2Classify * p1Vec) + log(pClass1)
    #计算[p(w|c2)*p(c2)]
    p0 = sum(vec2Classify * p0Vec) + log((1.0 - pClass1))
    if p1 > p0:
        return 1 
    else:
        return 0    

In [20]:
def testingNB():
    listOPosts, listClasses = loadDataSet()
    myVocabList = createVocabList(listOPosts)
    trainMat = []
    for postinDoc in listOPosts:
        trainMat.append(setOfWords2Vec(myVocabList, postinDoc))
    p0V, p1V, pAb = trainNB1(array(trainMat), array(listClasses))
    testEntry = ['love', 'my', 'dalmation']
    thisDoc = array(setOfWords2Vec(myVocabList, testEntry))
    print(testEntry,"classified as: ", classifyNB(thisDoc, p0V, p1V, pAb))
    testEntry = ["stupid", 'garbage']
    thisDoc = array(setOfWords2Vec(myVocabList, testEntry))
    print(testEntry,"classified as: ", classifyNB(thisDoc, p0V, p1V, pAb))
    

In [21]:
testingNB()

['love', 'my', 'dalmation'] classified as:  0
['stupid', 'garbage'] classified as:  1


In [18]:
def bagOfWords2Vec(vocabList, inputSet):
    returnVec = [0]*len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)] += 1#相当于加权
        else: print("the word: %s is not in my Vocabulary!")%word
    return returnVec

In [75]:
mySent = "This book is the best book on Python or M.L. I have ever laid eyes upon."
mySent.split()

['This',
 'book',
 'is',
 'the',
 'best',
 'book',
 'on',
 'Python',
 'or',
 'M.L.',
 'I',
 'have',
 'ever',
 'laid',
 'eyes',
 'upon.']

In [87]:
mySent

'This book is the best book on Python or M.L. I have ever laid eyes upon.'

In [22]:
def ExtractWords(emailDoc):
    import re
    regEx = re.compile(r'\b\w+\b')
    listOfTokens = regEx.findall(emailDoc)
    return [tok.lower() for tok in listOfTokens if len(tok) > 2]

In [23]:
def spamTest():
    docList = []
    classList = []
#     fullText = []
    for i in range(1, 26):
        wordList = ExtractWords(open('email/spam/%d.txt' % i).read())
        docList.append(wordList)
#         fullText.extend(wordList)
        classList.append(1)
        wordList = ExtractWords(open('email/ham/%d.txt' % i).read())
        docList.append(wordList)
#         fullText.extend(wordList)
        classList.append(0)
    vocabList = createVocabList(docList)
    trainingSet = list(range(50))
    testSet = []
    for i in range(10):
        randIndex = int(random.uniform(0, len(trainingSet)))
        testSet.append(trainingSet[randIndex])
        del(trainingSet[randIndex])
    trainMat = []
    trainClasses = []
    for docIndex in trainingSet:
        trainMat.append(bagOfWords2Vec(vocabList, docList[docIndex]))
        trainClasses.append(classList[docIndex])
    p0V, p1V, pSpam = trainNB1(array(trainMat), array(trainClasses))
    errorCount = 0
    for docIndex in testSet:
        wordVector = bagOfWords2Vec(vocabList, docList[docIndex])
        if classifyNB(array(wordVector), p0V, p1V, pSpam) != classList[docIndex]:
            errorCount += 1 
    print("the error rate is : ",float(errorCount/len(testSet)))


In [33]:
def spamTest():
    docList = []
    classList = []
#     fullText = []
    for i in range(1, 26):
        wordList = ExtractWords(open('email/spam/%d.txt' % i).read())
        docList.append(wordList)
#         fullText.extend(wordList)
        classList.append(1)
        wordList = ExtractWords(open('email/ham/%d.txt' % i).read())
        docList.append(wordList)
#         fullText.extend(wordList)
        classList.append(0)
    vocabList = createVocabList(docList)
    errorCount = 0
    totalTest = 0
    rate = 0
    for j in range(1000):
        trainingSet = list(range(50))
        testSet = []
        for i in range(10):
            randIndex = int(random.uniform(0, len(trainingSet)))
            testSet.append(trainingSet[randIndex])
            del(trainingSet[randIndex])
        trainMat = []
        trainClasses = []
        for docIndex in trainingSet:
            trainMat.append(bagOfWords2Vec(vocabList, docList[docIndex]))
            trainClasses.append(classList[docIndex])
        p0V, p1V, pSpam = trainNB1(array(trainMat), array(trainClasses))
        for docIndex in testSet:
            totalTest += 1
            wordVector = bagOfWords2Vec(vocabList, docList[docIndex])
            if classifyNB(array(wordVector), p0V, p1V, pSpam) != classList[docIndex]:
                errorCount += 1 
        rate += float(errorCount/totalTest)
    rate /= 1000.0
    print( "the error rate is : ",rate)

In [34]:
spamTest()

the error rate is :  0.06678917468611888


In [269]:
import feedparser
ny = feedparser.parse('http://newyork.craigslist.org/stp/index.rss')

In [270]:
ny['entries']

[]

In [271]:
ny

{'bozo': 1,
 'entries': [],
 'feed': {'summary': 'Your request has been blocked.<br /><br />If you have questions, please <a href="https://www.craigslist.org/contact?step=form&amp;reqType=help_blocks&amp;blockID=39468">contact us</a>'},
 'headers': {'content-length': '248',
  'set-cookie': 'cl_b=4|f214e06b299b1e3f3b725f6297a1999f64fd1214|1689342929eDpZk;path=/;domain=.craigslist.org;secure;expires=Fri, 01-Jan-2038 00:00:00 GMT',
  'strict-transport-security': 'max-age=63072000'},
 'href': 'https://newyork.craigslist.org/stp/index.rss',
 'status': 301,
 'encoding': 'iso-8859-1',
 'bozo_exception': xml.sax._exceptions.SAXParseException('not well-formed (invalid token)'),
 'version': '',
 'namespaces': {}}